### ISSUE TITLE
Latest nmi_mysql not working due to incorrect import

### ISSUE THREAD

**Issue by sibayanjasper** [pprmint/nmi_mysql#15]
ImportError: No module named 'utils' at line [nmi_mysql.py#L9](https://github.com/pprmint/nmi_mysql/blob/master/nmi_mysql/nmi_mysql.py#L9).

Quick fix is to replace the line with `from nmi_mysql.utils import deprecated` or `from .utils import deprecated`

**Comment by ninnzz** [comment]
Lol, may issue, di naka reference ung PR.. haha.. reference mo ung PR next time.

**Comment by ninnzz** [comment]
#16

**Comment by ninnzz** [comment]
Close mo n lng pag natest mo na.

**Comment by sibayanjasper** [comment]
@pprmint okay na. Thanks.
